# Title: Number of Prints in French Libraries, sorted by decade
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rism: <https://rism.online/api/v1#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT (STR(?dec) AS ?decade) (COUNT(DISTINCT ?source) AS ?count) WHERE {
?source a rism:Source ;
        rism:hasDates/rism:earliestDate ?date ;
        rism:holdings/rism:hasHolding ?copy .

MINUS {
  ?source rism:partOf/rism:isPartOf ?parent .
}

?copy rism:hasHoldingInstitution ?institution .
?institution rism:hasCountryCodes "F" .

BIND((FLOOR(?date / 10) * 10) AS ?dec)
}
GROUP BY ?dec
HAVING(?dec > 1490 && ?dec < 2100)
ORDER BY ?dec
