# Title: People in RISM listed as a dedicatee, by unique institution
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rism: <https://rism.online/api/v1#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX relators: <http://id.loc.gov/vocabulary/relators/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?person (?pName AS ?name) (COUNT(DISTINCT ?institution) AS ?count)
WHERE {
?source a rism:Source ;
        rism:materialGroups/rism:hasMaterialGroup ?materialGroup ;
        rism:holdings/rism:hasHolding ?copy .

?materialGroup rism:hasSummary ?group ;
               rism:relationships/rism:hasRelationship ?dte .

?dte dcterms:relation ?person ;
     rism:hasRole relators:dte .

?group a dcterms:type ;
       rdf:value ?source_type .

?copy rism:hasHoldingInstitution ?institution .

?person a rism:Person ;
        rdfs:label ?pName .

FILTER(LANG(?pName) = "none")

# FILTER(?source_type = "Autograph manuscript"@en)
}
GROUP BY ?person ?pName
HAVING(COUNT(DISTINCT ?institution) > 1)
ORDER BY DESC(?count)
