# Title: List of people as dedicatees by number of sources
PREFIX rism: <https://rism.online/api/v1#>
  PREFIX dcterms: <http://purl.org/dc/terms/>
  PREFIX relators: <http://id.loc.gov/vocabulary/relators/>
  PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

  SELECT ?person (SAMPLE(?name) AS ?personName) (COUNT(DISTINCT ?source) AS ?dedicateeCount) WHERE {
    ?source rism:hasRelationship ?rel .
    ?rel rism:hasRole relators:dte ;
         dcterms:relation ?person .

    ?person rdfs:label ?name .
  }
  GROUP BY ?person
  ORDER BY DESC(?dedicateeCount)
  LIMIT 100
