# Title: List of people in RISM with portraits in Wikidata
PREFIX rism: <https://rism.online/api/v1#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX relators: <http://id.loc.gov/vocabulary/relators/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>

SELECT ?composer ?composer_id ?wiki_id ?picture
WHERE {
    {
      SELECT DISTINCT ?composer ?composer_id ?composer_id_str
      WHERE {
        ?source a rism:Source ;
                dcterms:creator ?creator .

        ?creator dcterms:relation ?composer_id ;
                 rism:hasRole relators:cre .

        ?composer_id rdfs:label ?composer .
        FILTER(LANG(?composer) = "none")

        BIND(REPLACE(STR(?composer_id), "^https?://[^/]+/", "") AS ?composer_id_str)
      }
    }

    SERVICE <https://query.wikidata.org/sparql> {
      ?wiki_id wdt:P5504 ?composer_id_str ;
               wdt:P18 ?picture .
    }
}
GROUP BY ?composer_id ?composer ?wiki_id ?picture
